apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-runner-sa
  namespace: dotnet-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner-rb
  namespace: dotnet-app
subjects:
- kind: ServiceAccount
  name: gitlab-runner-sa
  namespace: dotnet-app
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io